//DEPLOYMENT ID
export const token="QmbLbV9gdcw1xZ5rFbmg5NmafybZC6fd5PYoV4HzCUgyXJ"//"QmSwaV58pwhwoUs3LnZqqRyHMQagGAr58XquCaQxmEmKdb"
export const tokenForBalance="QmYLp4WZKRnoLKy38xZodn1WNRaZVBoMJwWA6mZ34w4eQo"//QmThVMbzn2HdxyabvifzGupXgbiLStUpzxZ3mdWoB9Z7zj
